import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useEffect, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

type TPokemonItem = {
  name: string;
  url: string;
};

type TNavigationObj = {
  next: string | null;
  prev: string | null;
};

export default function Home() {
  const [pokeList, setPokeList] = useState<TPokemonItem[]>([]);
  const [navigation, setNavigation] = useState<TNavigationObj>({
    next: null,
    prev: null,
  });
  const [isLoading, setIsLoading] = useState(false);

  useEffect(() => {
    setIsLoading(true);
    fetch("https://pokeapi.co/api/v2/pokemon")
      .then((res) => res.json())
      .then((result): void => {
        setPokeList(result.results);
        setNavigation({
          next: result.next,
          prev: result.previous,
        });
      })
      .finally(() => setIsLoading(false));
  }, []);

  const onNavHandle = (type: "prev" | "next") => {
    setIsLoading(true);
    fetch(type === "next" ? navigation.next ?? "" : navigation.prev ?? "")
      .then((res) => res.json())
      .then((result): void => {
        setPokeList(result.results);
        setNavigation({
          next: result.next,
          prev: result.previous,
        });
      })
      .finally(() => setIsLoading(false));
  };

  return (
    <>
      <Head>
        <title>Pokemon List</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="text-center my-4">
        <h1>Pokemon List</h1>
      </div>
      <div
        className="d-flex justify-content-center mx-4 my-4"
        style={{ gap: "1rem" }}
      >
        <button
          className="btn btn-info"
          onClick={() => onNavHandle("prev")}
          disabled={navigation.prev === null}
        >
          Prev
        </button>
        <button
          className="btn btn-info"
          onClick={() => onNavHandle("next")}
          disabled={navigation.next === null}
        >
          Next
        </button>
      </div>
      <div className="container text-center">
        {isLoading ? (
          <div
            className="progress"
            role="progressbar"
            aria-label="Animated striped example"
            aria-valuenow={75}
            aria-valuemin={0}
            aria-valuemax={100}
            style={{
              height: "0.5rem",
            }}
          >
            <div
              className="progress-bar progress-bar-striped progress-bar-animated"
              style={{ width: "100%" }}
            ></div>
          </div>
        ) : (
          <div style={{ height: "0.5rem" }} />
        )}
        <div>
          <table className="table table-striped table-bordered">
            <thead>
              <tr>
                <th>Name</th>
                <th>Url</th>
              </tr>
            </thead>
            <tbody>
              {pokeList.map((item) => (
                <tr key={item.name}>
                  <td>{item.name}</td>
                  <td>{item.url}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </>
  );
}
