import Head from "next/head";
import { FC } from "react";
import { TNavigationObj, TPokemonItem } from ".";
import style from "@/styles/Home.module.css";

type TPokemonListProps = {
  onNavHandle: (type: "prev" | "next") => void;
  navigation: TNavigationObj;
  pokeList: TPokemonItem[];
  isLoading: boolean;
  isFetching: boolean;
};

const PokemonList: FC<TPokemonListProps> = ({
  navigation,
  onNavHandle,
  isLoading,
  pokeList,
  isFetching,
}) => {
  return (
    <>
      <Head>
        <title>Pokemon List</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {isFetching && (
        <div className={style.loading_screen}>
          <div className="spinner-border text-primary" role="status">
            <span className="sr-only"></span>
          </div>
          <span>Please Wait...</span>
        </div>
      )}
      <div className="text-center my-4">
        <h1>Pokemon List</h1>
      </div>
      <div
        className="d-flex justify-content-center mx-4 my-4"
        style={{ gap: "1rem" }}
      >
        <button
          className="btn btn-info"
          onClick={() => onNavHandle("prev")}
          disabled={navigation.prev === null}
        >
          Prev
        </button>
        <button
          className="btn btn-info"
          onClick={() => onNavHandle("next")}
          disabled={navigation.next === null}
        >
          Next
        </button>
      </div>
      <div className="container text-center">
        {isLoading ? (
          <div
            className="progress"
            role="progressbar"
            aria-label="Animated striped example"
            aria-valuenow={75}
            aria-valuemin={0}
            aria-valuemax={100}
            style={{
              height: "0.5rem",
            }}
          >
            <div
              className="progress-bar progress-bar-striped progress-bar-animated"
              style={{ width: "100%" }}
            ></div>
          </div>
        ) : (
          <div style={{ height: "0.5rem" }} />
        )}
        <div>
          <table className="table table-striped table-bordered">
            <thead>
              <tr>
                <th>Name</th>
                <th>Url</th>
              </tr>
            </thead>
            <tbody>
              {pokeList.map((item) => (
                <tr key={item.name}>
                  <td>{item.name}</td>
                  <td>{item.url}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </>
  );
};

export default PokemonList;
